# -*- coding: utf-8 -*-
"""Topic modeling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TVLPMPkqujsJ3FgkBNk3ldJzSUJE45co

#Installation des dépendances


Dans cette section, nous installons les bibliothèques nécessaires à la réalisation de la modélisation thématique.

Nous utilisons BERTopic pour l’extraction automatique de sujets, spaCy pour le traitement linguistique avancé, et langdetect pour l’identification de la langue des textes.

Nous téléchargeons également les modèles linguistiques français et anglais de spaCy afin de permettre une analyse multilingue des données.
"""

# installation
!pip install bertopic spacy langdetect
!python -m spacy download fr_core_news_sm
!python -m spacy download en_core_web_sm

"""#  Importation des bibliothèques


Dans cette étape, nous importons l’ensemble des bibliothèques nécessaires au traitement des données textuelles et à la modélisation thématique.

Ces outils couvrent :
- la manipulation de données
- le traitement du langage naturel (NLP)
- la détection de langue
- la modélisation thématique avec BERTopic
- la vectorisation des textes

Les bibliothèques utilisées permettent de construire un pipeline complet d’analyse de textes multilingues (français et anglais).
"""

import pandas as pd
import numpy as np
import datetime as dt

from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer

import spacy
from langdetect import detect

import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

"""#  Chargement et préparation des données


Dans cette étape, nous chargeons le jeu de données contenant les articles collectés.

Nous effectuons ensuite un premier nettoyage afin de garantir la qualité des analyses :
- suppression des valeurs manquantes dans le texte
- suppression des textes vides ou constitués uniquement d’espaces
- conversion de la date au format datetime pour permettre les analyses temporelles
"""

#chargement des données

dataset_path = "https://raw.githubusercontent.com/GuerindaG/equipe6_benin_insight_challenge_2026/refs/heads/machine_learning_engineer/models/outputs/scraped_articles.csv"
df = pd.read_csv(dataset_path)

df = df.dropna(subset=['text'])
df = df[df['text'].str.strip() != ""]

#conversion de la date
df['date_datetime'] = pd.to_datetime(df['SQLDATE'], errors='coerce')

"""# Chargement des modèles linguistiques

##  Préparation du traitement multilingue

Nous chargeons ici les modèles linguistiques de spaCy pour le français et l’anglais.

Cela permet d’effectuer un traitement adapté selon la langue du texte (lemmatisation, analyse grammaticale, etc.).

Nous définissons également une liste de mots vides (stopwords) afin de filtrer les mots peu informatifs dans les textes.
"""

#chargemnt des modèles de spacy

nlp_fr = spacy.load("fr_core_news_sm")
nlp_en = spacy.load("en_core_web_sm")

stop_words = set(stopwords.words('english') + stopwords.words('french'))

"""# Prétraitement des textes

##  Nettoyage et normalisation

Nous définissons à ce niveau une fonction de prétraitement des textes.

Cette fonction permet :
- d’identifier automatiquement la langue du texte (français ou anglais)
- de sélectionner le modèle spaCy adapté
- de normaliser le texte (minuscules, lemmatisation)
- de supprimer les mots vides (stopwords)
- de filtrer les tokens non pertinents

L’objectif est d’obtenir une représentation propre et exploitable pour la modélisation thématique.


Nous appliquons ensuite la fonction de prétraitement à l’ensemble des textes du dataset.

Chaque article est transformé en une version nettoyée et normalisée, prête pour la modélisation thématique.

Nous obtenons ensuite une liste de documents exploitables par le modèle BERTopic.
"""

#prétraitement

def preprocess_text(text):
    try:
        lang = detect(text)
    except:
        return ""

    # Choisir modèle selon langue
    nlp = nlp_fr if lang == "fr" else nlp_en

    doc = nlp(text.lower())

    tokens = []
    for token in doc:
        if (
            token.is_alpha and
            token.lemma_ not in stop_words and
            len(token.lemma_) > 2
        ):
            tokens.append(token.lemma_)

    return " ".join(tokens)

#application du preprocessing

df['clean_text'] = df['text'].apply(preprocess_text)

docs = df['clean_text'].tolist()

"""# Vectorisation des textes

## Transformation en représentation numérique

Nous transformons les textes en une représentation exploitable par le modèle de machine learning.

Nous utilisons une vectorisation basée sur les n-grammes (1 à 2 mots), ce qui permet de capturer des expressions importantes plutôt que des mots isolés.

Nous filtrons également les termes trop rares afin de réduire le bruit dans les données.
"""

#vectorization

vectorizer_model = CountVectorizer(
    ngram_range=(1,2),
    stop_words=list(stop_words),
    min_df=10
)

"""# Entraînement du modèle BERTopic

##  Construction du modèle de topics

Dans cette étape, nous entraînons le modèle BERTopic afin d’extraire automatiquement les thématiques présentes dans les textes.

Le modèle utilise :
- un modèle d’embedding multilingue pour représenter les textes
- la vectorisation basée sur les n-grammes définie précédemment
- un paramètre de taille minimale de topics pour éviter les sujets trop petits

L’objectif est d’obtenir des thèmes cohérents et interprétables.
"""

#entrainement du modèle

topic_model = BERTopic(
    embedding_model="paraphrase-multilingual-MiniLM-L12-v2",
    vectorizer_model=vectorizer_model,
    min_topic_size=10,
    verbose=True
)

topics, probs = topic_model.fit_transform(docs)

"""
Nous affichons un résumé des principaux groupes thématiques détectés, incluant :
- le numéro du topic
- le nom représentatif du topic
- le nombre de documents associés

Cette étape permet de vérifier la cohérence et la qualité des sujets extraits."""

topic_info = topic_model.get_topic_info()
print(topic_info.head(10))

topic_model.get_topic(0)

topic_model.visualize_topics()

"""# Évolution des topics dans le temps

## Analyse temporelle des thématiques

Nous analysons l’évolution des topics dans le temps.

Cette visualisation permet de comprendre :
- comment les sujets évoluent sur la période étudiée
- quels thèmes sont dominants à certains moments
- les tendances globales dans les données textuelles

Cette analyse est particulièrement utile pour détecter des événements ou des changements de narration.
"""

topics_over_time = topic_model.topics_over_time(docs, df['date_datetime'])
topic_model.visualize_topics_over_time(topics_over_time)

topic_model.generate_topic_labels()

"""À présent, examinons comment les articles initiaux sur le Bénin ont été mis en correspondance avec les sujets identifiés."""

df_docs = topic_model.get_document_info(docs)
df_docs.head(10)

"""Passons maintenant en revue les statistiques récapitulatives de la répartition des avis par thèmes identifiés."""

freq = topic_model.get_topic_info()
freq.head(10)

"""On constate qu'une part importante des articles est considérée comme aberrante

---

et est donc regroupée dans la catégorie fourre-tout « Autres » (avec la valeur -1 pour le sujet).

 Visualisons maintenant le nombre d'articles par sujet identifié, à l'exclusion du sujet fourre-tout « Autres ».
"""

import plotly.express as px
topic_freq = freq[freq['Topic'] > -1]
fig = px.bar(topic_freq, x='Name', y='Count',
             title='Review Count by Topics',
            color_discrete_sequence=px.colors.qualitative.Prism)
fig.show()

"""Visualisons les termes (mots) les plus fréquents qui sont apparus dans les articles concernant les principaux sujets abordés."""

topic_model.visualize_barchart(top_n_topics=10, height=700)

topic_model.visualize_term_rank()

topic_model.visualize_term_rank(log_scale=True)